name: api-ci-pipeline
env:
  AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
  AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
  AWS_DEFAULT_REGION: ${{secrets.AWS_DEFAULT_REGION}} 
  SLACK_WEBHOOK_URL: ${{secrets.SLACK_WEBHOOK_URL}}
on:
  push:
    branches:
      - master
    paths:
      - 'Dockerfile'
      - '.deploy/**'
      - '.github/workflows/**'
      - 'src/**' 
  pull_request:
    branches:
      - master

jobs:
  test:
    name: run test with Mocha
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: setup node environment
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm ci
      - run: npm test 

      - name: slack notification  
        uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
          channel: '#devops'
        if: always() 

  build-and-push-docker-image:
    name: build and push docker image
    runs-on: ubuntu-latest
    needs: test
    environment: nomad-stage
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2
      - run: docker login --username ${{secrets.DOCKER_USERNAME}} --password ${{secrets.DOCKER_PASSWORD}}    
      - run: docker build -t courageabam/nomad .
      - run: docker push courageabam/nomad
  build-ami:
    name: build ami
    env:
      PKR_VAR_docker_username: ${{secrets.DOCKER_USERNAME}}
      PKR_VAR_docker_password: ${{secrets.DOCKER_PASSWORD}}
    environment: nomad-stage
    runs-on: ubuntu-latest
    needs: build-and-push-docker-image
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2
      - name: install packer
        run: bash .deploy/scripts/packer-install.sh
      - name: validate packer image
        run: cd .deploy/packer && packer validate image.pkr.hcl
      - name: build packer image
        run: cd .deploy/packer && packer build image.pkr.hcl  
     

