name: api-ci-pipeline
env:
  AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
  AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
  AWS_DEFAULT_REGION: ${{secrets.AWS_DEFAULT_REGION}} 
on:
  push:
    branches:
      - master
    paths:
      - 'Dockerfile'
      - '.deploy/**'
      - '.github/workflows/**'
      - 'src/**' 
  pull_request:
    branches:
      - master

jobs:
  test:
    name: run test with Mocha
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: setup node environment
        uses: action/setup-node@v2
        with:
          node-version: '16'
      - run: npm ci
      - run: npm test    
